//> using scala "3.8.2"
//> using jvm "graalvm-community:24.0.1"
//> using dep "dev.zio::zio:2.1.24"
//> using dep "dev.zio::zio-json:0.9.0"
//> using dep "com.github.pathikrit::better-files:3.9.2"
//> using dep "com.lihaoyi::mainargs:0.7.8"
//> using file "src/domain.scala"
//> using file "src/task.scala"
//> using file "src/repo.scala"
//> using file "src/worktree.scala"
//> using file "src/mcp.scala"
//> using file "src/idea.scala"
//> using file "src/app.scala"
//> using file "src/ork.scala"
//> using option "-Wconf:msg=match may not be exhaustive:e"
